# Generated by Django 5.0.7 on 2024-07-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_filemodel_alter_month_options_entry_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='concepto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
